version: '3'

networks:
  todo-network:

services:
  todo_app:
    container_name: todo-app
    build: ./.docker/local/go
    ports:
      - 8081:8080
    env_file:
      - ./.docker/local/.env
    volumes:
      - .:/go-workspace/src/github.com/ashishkumar68/go-todo
    links:
      - todo_db
    networks:
      - todo-network
    hostname: todo_app

  todo_db:
    container_name: todo-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: todoapp
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: read_model
    networks:
      - todo-network